### ISSUE TITLE
steem.broadcast.transfer is broken

### ISSUE THREAD

**Issue by hazinstore** [adcpm/steem#37]
Calling 
`steem.broadcast.transfer(wif, source, to, amount, memo, function(err, result) {
                console.log(err, result);
                if(err){
                    deferred.reject(err);
                }else{
                    deferred.resolve(result);
                }
            });`

produces no errors, the only thing in the console is...
`null undefined`

So no output at all and the blockchain is showing no activity at all.
I've verified that all parameters are correct and I'm using my active key in Wif format for this.
This is done in the browser with the latest build of `<script src="lib/steem/dist/steem.min.js"></script>`

**Comment by hazinstore** [comment]
@pharesim Mentioned the lib has problems with WIF keys and to try it in PrivateKey format, I get the same result though.  Something is seriously busted here.

**Comment by adcpm** [comment]
Can you tell me the params you are using?

**Comment by adcpm** [comment]
Please try version the last version v0.3.30 it should fix this issue (the CDN has been updated).

**Comment by williambanks** [comment]
Problem is back, only now it just says...
steem.broadcast.transfer(...) is not a function
Immediately after broadcasting the transfer.

**Comment by adcpm** [comment]
I'm not able to reproduce this issue, can you open a new GitHub issue with more details. Are you using Steem.js on browser or server? which version and how to reproduce the issue.
